#!/usr/bin/env python3
"""
Generate Anomaly Detection Reports
Creates Markdown and JSON reports from detection results.
"""

import os
import json
import sys
import types as _types
from datetime import datetime

# Stub torch so loglizer's DeepLog import doesn't fail when torch isn't installed
if 'torch' not in sys.modules:
    _torch_stub = _types.ModuleType('torch')
    class _FakeTensor:
        pass
    _torch_stub.Tensor = _FakeTensor
    _torch_stub.nn = _types.ModuleType('torch.nn')
    _torch_stub.nn.Module = object
    _torch_stub.optim = _types.ModuleType('torch.optim')
    sys.modules['torch'] = _torch_stub
    sys.modules['torch.nn'] = _torch_stub.nn
    sys.modules['torch.optim'] = _torch_stub.optim


def generate_markdown_report(results, model_info, output_file='reports/report.md'):
    """Generate Markdown anomaly report."""
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    summary = results['summary']
    anomalies = results['anomaly']
    
    report_lines = [
        "# Log Analysis Report",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Sessions | {summary['total_sessions']} |",
        f"| Normal Sessions | {summary['normal_count']} |",
        f"| Anomalous Sessions | {summary['anomaly_count']} |",
        f"| Detection Rate | {(summary['anomaly_count'] / summary['total_sessions'] * 100):.1f}% anomaly rate |" if summary['total_sessions'] > 0 else f"| Detection Rate | N/A |",
        "",
        "---",
        "",
        "## Model Information",
        "",
        f"- **Model Type:** PCA (Principal Component Analysis)",
        f"- **Training Sessions:** {model_info.get('num_sessions', 'N/A')}",
        f"- **Training Events:** {model_info.get('num_events', 'N/A')}",
        f"- **Event Templates:** {len(model_info.get('event_templates', {}))}",
        f"- **Trained At:** {model_info.get('trained_at', 'N/A')}",
        "",
        "---",
        "",
        "## Detected Anomalies",
        "",
    ]
    
    if not anomalies:
        report_lines.extend([
            "**No anomalies detected.** All sessions exhibited normal behavior patterns.",
            ""
        ])
    else:
        for i, anomaly in enumerate(anomalies, 1):
            report_lines.append(f"### Anomaly #{i}")
            report_lines.append("")
            report_lines.append(f"**Session Index:** {anomaly['session_index']}")
            report_lines.append(f"**Event Count:** {anomaly['event_count']}")
            report_lines.append("")
            
            if anomaly['indicators']:
                report_lines.append("**Detected Issues:**")
                report_lines.append("")
                for indicator in anomaly['indicators']:
                    report_lines.append(f"- {indicator}")
                report_lines.append("")
            
            if anomaly['events_preview']:
                report_lines.append("**Event Preview:**")
                report_lines.append("")
                report_lines.append("```")
                for event in anomaly['events_preview'][:5]:
                    report_lines.append(event)
                report_lines.append("```")
                report_lines.append("")
    
    report_lines.extend([
        "---",
        "",
        "## Event Templates",
        "",
        "The following event templates were used for pattern recognition:",
        "",
    ])
    
    for event_id, template in sorted(model_info.get('event_templates', {}).items()):
        report_lines.append(f"- `{template}`")
    
    report_lines.extend([
        "",
        "---",
        "",
        "*This report was automatically generated by Loglizer Anomaly Detection Pipeline.*"
    ])
    
    with open(output_file, 'w') as f:
        f.write('\n'.join(report_lines))
    
    print(f"Markdown report saved to {output_file}")
    return output_file


def generate_summary_json(results, model_info, output_file='reports/summary.json'):
    """Generate JSON summary for dashboards."""
    summary_data = {
        'timestamp': datetime.now().isoformat(),
        'summary': results['summary'],
        'model': {
            'type': 'PCA',
            'training_sessions': model_info.get('num_sessions', 0),
            'training_events': model_info.get('num_events', 0),
            'event_templates_count': len(model_info.get('event_templates', {}))
        },
        'anomalies': [
            {
                'session_index': a['session_index'],
                'event_count': a['event_count'],
                'indicators': a['indicators']
            }
            for a in results['anomaly']
        ]
    }
    
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    with open(output_file, 'w') as f:
        json.dump(summary_data, f, indent=2)
    
    print(f"Summary JSON saved to {output_file}")
    return output_file


def main():
    """Generate reports from detection results."""
    anomalies_file = 'reports/anomalies.json'
    model_file = 'ml/model.pkl'
    
    if not os.path.exists(anomalies_file):
        print("Error: No detection results found. Run detect.py first.")
        return 1
    
    import pickle
    with open(anomalies_file, 'r') as f:
        results = json.load(f)
    
    with open(model_file, 'rb') as f:
        model_data = pickle.load(f)
    
    model_info = {
        'num_sessions': model_data.get('num_sessions', 0),
        'num_events': model_data.get('num_events', 0),
        'trained_at': model_data.get('trained_at', 'unknown'),
        'event_templates': model_data.get('event_templates', {})
    }
    
    print("Generating reports...")
    generate_markdown_report(results, model_info)
    generate_summary_json(results, model_info)
    
    print("\nReport generation complete!")
    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main())